package org.cgiar.ccafs.marlo.data.model;
// Generated Jan 8, 2019 3:50:56 PM by Hibernate Tools 5.3.6.Final

import org.cgiar.ccafs.marlo.data.IAuditLog;

import java.util.Date;

import com.google.gson.annotations.Expose;

/**
 * ProjectPolicyInfo generated by hbm2java
 */
public class ProjectActivityInfo extends MarloBaseEntity implements java.io.Serializable, IAuditLog {

  private static final long serialVersionUID = 2885275104787062400L;
  @Expose
  private Phase phase;
  @Expose
  private ProjectActivity projectActivity;
  @Expose
  private String title;
  @Expose
  private String description;
  @Expose
  private Date startDate;
  @Expose
  private Date endDate;
  @Expose
  private ProjectPartnerPerson projectPartnerPerson;
  @Expose
  private GeneralStatus activityStatus;
  @Expose
  private String activityProgress;


  public ProjectActivityInfo() {

  }


  public ProjectActivityInfo(Phase phase, ProjectActivity projectActivity) {
    super();
    this.phase = phase;
    this.projectActivity = projectActivity;
  }

  public String getActivityProgress() {
    return activityProgress;
  }


  public GeneralStatus getActivityStatus() {
    return activityStatus;
  }

  public String getDescription() {
    return description;
  }


  public Date getEndDate() {
    return endDate;
  }


  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }


  @Override
  public String getModificationJustification() {
    return "";
  }


  @Override
  public User getModifiedBy() {
    User u = new User();
    u.setId(new Long(3));
    return u;
  }


  public Phase getPhase() {
    return phase;
  }


  public ProjectActivity getProjectActivity() {
    return projectActivity;
  }


  public ProjectPartnerPerson getProjectPartnerPerson() {
    return projectPartnerPerson;
  }


  public Date getStartDate() {
    return startDate;
  }


  public String getTitle() {
    return title;
  }


  @Override
  public boolean isActive() {
    return true;
  }


  public void setActivityProgress(String activityProgress) {
    this.activityProgress = activityProgress;
  }


  public void setActivityStatus(GeneralStatus activityStatus) {
    this.activityStatus = activityStatus;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public void setEndDate(Date endDate) {
    this.endDate = endDate;
  }


  @Override
  public void setModifiedBy(User modifiedBy) {

  }


  public void setPhase(Phase phase) {
    this.phase = phase;
  }


  public void setProjectActivity(ProjectActivity projectActivity) {
    this.projectActivity = projectActivity;
  }


  public void setProjectPartnerPerson(ProjectPartnerPerson projectPartnerPerson) {
    this.projectPartnerPerson = projectPartnerPerson;
  }


  public void setStartDate(Date startDate) {
    this.startDate = startDate;
  }


  public void setTitle(String title) {
    this.title = title;
  }


  @Override
  public String toString() {
    return "ProjectActivityInfo [id=" + this.getId() + "ProjectActivity=" + projectActivity + ", phase=" + phase
      + ", title=" + title + "]";
  }

  /**
   * Add the save information to reply the next Phase
   * 
   * @param projectInnovationInfoUpdate - a ProjectInnovationInfo object.
   * @param phase - The next Phase
   */
  // public void updateProjectPolicyInfo(ProjectActivityInfo projectPolicyInfoUpdate, Phase phase) {
  //
  // this.setPhase(phase);
  //
  // this.setTitle(projectPolicyInfoUpdate.getTitle());
  // this.setAmount(projectPolicyInfoUpdate.getAmount());
  // this.setYear(projectPolicyInfoUpdate.getYear());
  // this.setRepIndStageProcess(projectPolicyInfoUpdate.getRepIndStageProcess());
  // this.setRepIndPolicyInvestimentType(projectPolicyInfoUpdate.getRepIndPolicyInvestimentType());
  // this.setRepIndOrganizationType(projectPolicyInfoUpdate.getRepIndOrganizationType());
  // this.setRepIndGeographicScope(projectPolicyInfoUpdate.getRepIndGeographicScope());
  // this.setProjectPolicy(projectPolicyInfoUpdate.getProjectPolicy());
  // this.setProjectExpectedStudy(projectPolicyInfoUpdate.getProjectExpectedStudy());
  // this.setOther(projectPolicyInfoUpdate.getOther());
  //
  // }


}

