package org.cgiar.ccafs.marlo.data.model;
// Generated Apr 10, 2018 10:49:03 AM by Hibernate Tools 5.2.5.Final


/**
 * BiPermissions generated by hbm2java
 */
public class BiPermissions implements java.io.Serializable {


  private Long id;
  private Long type;
  private Long user;
  private String urlbi;
  private String userBi;
  private String userPass;
  private boolean isActive;

  public BiPermissions() {
  }


  public BiPermissions(boolean isActive) {
    this.isActive = isActive;
  }

  public BiPermissions(Long type, Long user, String urlbi, String userBi, String userPass, boolean isActive) {
    this.type = type;
    this.user = user;
    this.urlbi = urlbi;
    this.userBi = userBi;
    this.userPass = userPass;
    this.isActive = isActive;
  }

  public Long getId() {
    return this.id;
  }

  public Long getType() {
    return this.type;
  }

  public String getUrlbi() {
    return this.urlbi;
  }

  public Long getUser() {
    return this.user;
  }

  public String getUserBi() {
    return userBi;
  }

  public String getUserPass() {
    return userPass;
  }

  public boolean isIsActive() {
    return this.isActive;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public void setIsActive(boolean isActive) {
    this.isActive = isActive;
  }

  public void setType(Long type) {
    this.type = type;
  }


  public void setUrlbi(String urlbi) {
    this.urlbi = urlbi;
  }


  public void setUser(Long user) {
    this.user = user;
  }


  public void setUserBi(String userBi) {
    this.userBi = userBi;
  }


  public void setUserPass(String userPass) {
    this.userPass = userPass;
  }


}

